name: common-qa-workflow

on:
  workflow_dispatch:
  push:
    branches: 
      - proof-v10-qa-*
    paths:
      - api/**/**
      - '!api/k8s/**'
      - assessment/**/**
      - '!assessment/k8s/**'
      - data-processing/**/**
      - '!data-processing/k8s/**'
      - workers/**/**
      - '!workers/assessment-due/k8s/**'
      - '!workers/metric-aggregate/k8s/**'
      - '!workers/metric-calculate/k8s/**' 

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  id-token: write

jobs:
  services_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for Push
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        uses: actions/checkout@v2
        with:
           fetch-depth: 0 
           ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout for Tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/checkout@v2
        with:
           fetch-depth: 0

      - name: Create Files Array
        id: createarray
        run: |-
          echo "Create Files Array"

  build-push-gcr:
    needs: services_list
    runs-on: ubuntu-latest
    steps:
    - name: Checkout on Tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Checkout on Push
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
