name: common-qa-workflow

on:
  workflow_dispatch:
  push:
    branches: 
      - test-branch-protection-rules
    paths:
      - api/**/**
      - '!api/k8s/**'
      - assessment/**/**
      - '!assessment/k8s/**'
      - workers/**/**
      - '!workers/assessment-due/k8s/**'
      - '!workers/metric-aggregate/k8s/**'
      - '!workers/metric-calculate/k8s/**' 

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  id-token: write

jobs:
  services_list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout on Tag
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Commit Files
      run: |-
        temp=$(cat ./api/checkpoint | grep -Eo '[0-9]+' | head -n 1)
        ((temp++))
        echo $temp > ./api/checkpoint
        git add .
        git commit -m "Update checkpoint"

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: test-branch-protection-rules