name: staging-deployment

on:
  push:
    branches:
      - test/fix-commit-issue1
    paths:
      - api/**/**
      - '!api/k8s/**'
      - assessment/**/**
      - '!assessment/k8s/**'
      - data-processing/**/**
      - '!data-processing/k8s/**'
      - framework/**/**
      - '!framework/k8s/**'      
      - worker/**/**
      - '!worker/assessment-due/k8s/**'
      - '!worker/metric-aggregate/k8s/**'
      - '!worker/metric-calculate/k8s/**' 

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: read
  repository-projects: write
  security-events: write
  statuses: write
  id-token: write


jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          api: 
            - 'api/**/**'
          assessment: 
            - 'assessment/**/**'  
          data-processing: 
            - 'data-processing/**/**'  
          assessment-due: 
            - 'worker/assessment-due/**/**'    
        list-files: 'csv'

  build:
    needs: changes
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           fetch-depth: 10

      - name: create files array
        id: createarray
        run: |-
              echo "this is : ${{ matrix.package }} "
      
